### ISSUE TITLE
Add "sub" config for gNews feed

### ISSUE THREAD

**Issue by impredicative** [FingerlessGlov3s/SecurityFeedIRCBot#2]
Without the following config for the gNews feed, titles can often end with .com, .org, etc. Such suffixes for titles are needlessly distracting.

```yaml
      sub:
        title:  # Removes .com and similar suffixes.
          pattern: (?P<caption>.+) - (?P<source>.+?)\.(?:.+)
          repl: \g<caption> - \g<source>
```
